//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoom
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Amenities { get; set; }
        public string Description { get; set; }
        public string ImgAlt { get; set; }
        public Nullable<int> ImgWidth { get; set; }
        public Nullable<int> ImgHeight { get; set; }
        public string ImgExt { get; set; }
    }
}
